spring:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    # properties:
    #   hibernate:
    #     format_sql: true
    # database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password:


  # devtools:
  #   livereload:
  #     enabled: true
  #   restart:
  #     enabled: true
  #   add-properties: false # DevToolsPropertyDefaultsPostProcessor

  output:
    ansi:
      enabled: always # console color

# https://springdoc.org/#properties
springdoc:
  default-consumes-media-type: application/json # 기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용
  swagger-ui:
    enabled: true # default