spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 압축된 쿼리를 읽기 좋게 포멧
    generate-ddl: false # 자동으로 entity에서 활용하고있는것을 테이블을 만듦 (false: default)
    hibernate:
      ddl-auto: create-drop
    # defer-datasource-initialization: true # for h2 database
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 8516
    initialization-mode: always # spring에서 지정하는 initialization 모드 사용
server:
  port: 8080